<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Projet </title>
        <link rel="stylesheet" href="assets/styles/css/style.css">
    </head>
    <body>
    <section class="container">
    <header>
        <h1> THE LEAGUE</h1>
        <nav class="navBar">
            <ul class ="navBar-list">
            <li><a>LES TEAMS</a></li>
            <li><a>LES PLAYERS </a></li>
            <li><a>LES MATCHS </a></li>
        </ul>
        </nav>
    </header>
  <?phprequire_once "views/templates/partials/$partials"; ?>
</section>
    </body>
</html>

